import {
  Node,
  Server,
  Egg,
  QueueJob,
  AuditLogEntry,
  ApiToken,
  ActiveSession,
  BillingPlan,
  WebhookEndpoint,
  WhiteLabelConfig,
  User,
} from './types';

export const CURRENT_USER: User = {
  id: 'usr_superadmin_01',
  email: 'admin@controlpanel.gg',
  name: 'Maksym Bondar',
  role: 'superadmin',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  two_factor_enabled: true,
  two_factor_type: 'totp',
  created_at: '2026-01-15T10:00:00Z',
};

export const INITIAL_WHITE_LABEL: WhiteLabelConfig = {
  panel_name: 'ControlPanel',
  company_name: 'Apex Infrastructure Ltd',
  logo_text: 'ControlPanel',
  accent_color: 'emerald',
  support_url: 'https://help.controlpanel.gg',
  custom_footer: 'ControlPanel v1.0 • Next-Gen Game Server Platform (MIT)',
};

export const INITIAL_NODES: Node[] = [
  {
    id: 'node_fra_01',
    name: 'Frankfurt-01 (AMD EPYC)',
    fqdn: 'fra1.daemon.controlpanel.gg',
    ip: '194.26.29.102',
    region: 'Europe Central',
    country_code: 'DE',
    agent_version: 'v1.22.4 (Go rootless)',
    status: 'online',
    maintenance_mode: false,
    is_rootless: true,
    daemon_type: 'docker',
    latency_ms: 18,
    uptime_days: 94.2,
    cpu_cores: 64,
    cpu_usage_percent: 42,
    ram_total_mb: 131072, // 128 GB
    ram_used_mb: 74240,   // ~72 GB
    disk_total_gb: 4000,
    disk_used_gb: 1840,
    servers_count: 24,
    agent_token: 'cpa_live_fra1_99x811b7zqa0',
    alert_thresholds: {
      disk_warn_percent: 85,
      cpu_warn_percent: 90,
      notify_discord: true,
      notify_email: true,
    },
  },
  {
    id: 'node_waw_02',
    name: 'Warsaw-02 (Ryzen 7950X)',
    fqdn: 'waw2.daemon.controlpanel.gg',
    ip: '185.125.216.45',
    region: 'Eastern Europe',
    country_code: 'PL',
    agent_version: 'v1.22.4 (Go rootless)',
    status: 'online',
    maintenance_mode: false,
    is_rootless: true,
    daemon_type: 'podman',
    latency_ms: 24,
    uptime_days: 41.8,
    cpu_cores: 32,
    cpu_usage_percent: 58,
    ram_total_mb: 65536,  // 64 GB
    ram_used_mb: 41984,
    disk_total_gb: 2000,
    disk_used_gb: 1220,
    servers_count: 14,
    agent_token: 'cpa_live_waw2_84k271a3xpl1',
    alert_thresholds: {
      disk_warn_percent: 80,
      cpu_warn_percent: 85,
      notify_discord: true,
      notify_email: false,
    },
  },
  {
    id: 'node_hel_01',
    name: 'Helsinki-01 (Green Storage)',
    fqdn: 'hel1.daemon.controlpanel.gg',
    ip: '95.216.14.88',
    region: 'Nordics',
    country_code: 'FI',
    agent_version: 'v1.22.3 (Go rootless)',
    status: 'online',
    maintenance_mode: false,
    is_rootless: true,
    daemon_type: 'docker',
    latency_ms: 32,
    uptime_days: 120.5,
    cpu_cores: 48,
    cpu_usage_percent: 29,
    ram_total_mb: 98304,
    ram_used_mb: 32768,
    disk_total_gb: 8000,
    disk_used_gb: 3450,
    servers_count: 18,
    agent_token: 'cpa_live_hel1_11c944f2zfl0',
    alert_thresholds: {
      disk_warn_percent: 90,
      cpu_warn_percent: 90,
      notify_discord: true,
      notify_email: true,
    },
  },
  {
    id: 'node_iad_01',
    name: 'US-Virginia-01 (East Edge)',
    fqdn: 'iad1.daemon.controlpanel.gg',
    ip: '144.202.8.19',
    region: 'North America',
    country_code: 'US',
    agent_version: 'v1.22.4 (Go rootless)',
    status: 'maintenance',
    maintenance_mode: true,
    is_rootless: true,
    daemon_type: 'docker',
    latency_ms: 88,
    uptime_days: 15.1,
    cpu_cores: 32,
    cpu_usage_percent: 18,
    ram_total_mb: 65536,
    ram_used_mb: 18432,
    disk_total_gb: 2000,
    disk_used_gb: 410,
    servers_count: 6,
    agent_token: 'cpa_live_iad1_55p302b1xus9',
    alert_thresholds: {
      disk_warn_percent: 85,
      cpu_warn_percent: 85,
      notify_discord: true,
      notify_email: true,
    },
  },
];

export const INITIAL_EGGS: Egg[] = [
  {
    id: 'egg_minecraft_paper',
    name: 'PaperMC (High Performance)',
    game: 'Minecraft: Java Edition',
    category: 'games',
    icon: 'Pickaxe',
    docker_image: 'ghcr.io/pterodactyl/yolks:java_21',
    startup_command: 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar {{SERVER_JARFILE}} nogui',
    config_schema: {
      files: ['server.properties', 'paper-global.yml'],
      startup: ['SERVER_JARFILE', 'BUILD_NUMBER', 'JAVA_VERSION'],
    },
    variables: [
      { key: 'SERVER_JARFILE', name: 'Server Jar File', description: 'Name of the executable jar', default_value: 'paper.jar', user_viewable: true, user_editable: true, rules: 'required|string' },
      { key: 'BUILD_NUMBER', name: 'Paper Build', description: 'Latest recommended or specific build', default_value: 'latest', user_viewable: true, user_editable: true, rules: 'required|string' },
      { key: 'VIEW_DISTANCE', name: 'Render View Distance', description: 'Chunk render distance for clients', default_value: '10', user_viewable: true, user_editable: true, rules: 'numeric|min:4|max:32' },
    ],
    version: '1.21.4',
    author: 'ControlPanel Core Team',
    rating: 4.9,
    downloads: 14820,
    official: true,
    description: 'High performance Minecraft server software with async chunk generation, optimized ticking, and full Spigot/Bukkit plugin compatibility.',
    readme: 'Default port: 25565. Supports custom flags like Aikar\'s flags automatically applied.',
  },
  {
    id: 'egg_cs2',
    name: 'Counter-Strike 2 Dedicated',
    game: 'Counter-Strike 2',
    category: 'games',
    icon: 'Crosshair',
    docker_image: 'ghcr.io/pterodactyl/games:source2',
    startup_command: './cs2/game/bin/linuxsteamrt64/cs2 -dedicated +ip 0.0.0.0 -port {{SERVER_PORT}} +map {{SRCDS_MAP}} +game_type 0 +game_mode 1 +mapgroup {{MAPGROUP}}',
    config_schema: {
      files: ['cs2/game/csgo/cfg/server.cfg'],
      startup: ['SRCDS_MAP', 'MAPGROUP', 'STEAM_ACC'],
    },
    variables: [
      { key: 'SRCDS_MAP', name: 'Default Map', description: 'Initial map on boot', default_value: 'de_mirage', user_viewable: true, user_editable: true, rules: 'required|string' },
      { key: 'MAXPLAYERS', name: 'Max Players', description: 'Max client slots', default_value: '16', user_viewable: true, user_editable: true, rules: 'numeric' },
      { key: 'TICKRATE', name: 'Sub-tick Engine Rate', description: 'Sub-tick architecture mode', default_value: 'subtick', user_viewable: true, user_editable: false, rules: 'string' },
    ],
    version: '2026.02.1',
    author: 'Valve Community Labs',
    rating: 4.8,
    downloads: 8940,
    official: true,
    description: 'Native Linux CS2 dedicated server container with sub-tick network optimizations and automated SteamCMD updates.',
    readme: 'Requires GSLT token from Steam Game Server Account management.',
  },
  {
    id: 'egg_rust',
    name: 'Rust Vanilla & Oxide/uMod',
    game: 'Rust',
    category: 'games',
    icon: 'Flame',
    docker_image: 'ghcr.io/pterodactyl/games:rust',
    startup_command: './RustDedicated -batchmode +server.port {{SERVER_PORT}} +server.identity "rust_server" +server.seed {{SERVER_SEED}} +server.worldsize {{WORLD_SIZE}} +server.maxplayers {{MAX_PLAYERS}}',
    config_schema: {
      files: ['server/rust_server/cfg/server.cfg'],
      startup: ['SERVER_SEED', 'WORLD_SIZE', 'MAX_PLAYERS'],
    },
    variables: [
      { key: 'SERVER_SEED', name: 'Procedural Map Seed', description: 'Random seed for map generator', default_value: '133742', user_viewable: true, user_editable: true, rules: 'numeric' },
      { key: 'WORLD_SIZE', name: 'World Size (Meters)', description: 'Map scale in meters', default_value: '4000', user_viewable: true, user_editable: true, rules: 'numeric|min:1000|max:6000' },
      { key: 'OXIDE', name: 'Enable Oxide/uMod', description: 'Auto-install Oxide mod loader', default_value: '1', user_viewable: true, user_editable: true, rules: 'boolean' },
    ],
    version: '2026.03',
    author: 'Facepunch & Community',
    rating: 4.7,
    downloads: 11200,
    official: true,
    description: 'Fast-booting Rust dedicated container with automated wipe scheduling, procedural seed picker and Oxide mod integration.',
    readme: 'High RAM recommended (minimum 8GB for standard 4k maps).',
  },
  {
    id: 'egg_palworld',
    name: 'Palworld Dedicated Server',
    game: 'Palworld',
    category: 'games',
    icon: 'Gamepad2',
    docker_image: 'ghcr.io/pterodactyl/games:palworld',
    startup_command: './PalServer.sh -port={{SERVER_PORT}} -players={{MAX_PLAYERS}} -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS',
    config_schema: {
      files: ['Pal/Saved/Config/LinuxServer/PalWorldSettings.ini'],
      startup: ['MAX_PLAYERS', 'COMMUNITY_SERVER'],
    },
    variables: [
      { key: 'MAX_PLAYERS', name: 'Max Players', description: 'Player slots', default_value: '32', user_viewable: true, user_editable: true, rules: 'numeric' },
      { key: 'SERVER_NAME', name: 'Public Server Name', description: 'Shown in in-game server browser', default_value: 'ControlPanel Palworld Realm', user_viewable: true, user_editable: true, rules: 'string' },
    ],
    version: '0.4.12',
    author: 'ControlPanel Labs',
    rating: 4.8,
    downloads: 9400,
    official: true,
    description: 'Palworld server container with multithreading flags and memory-leak auto-cleaning hooks.',
    readme: 'Optimized with jemalloc memory allocator to prevent native memory degradation.',
  },
  {
    id: 'egg_fivem',
    name: 'FiveM FXServer (QBCore / ESX)',
    game: 'GTA V / FiveM',
    category: 'games',
    icon: 'Car',
    docker_image: 'ghcr.io/pterodactyl/games:fivem',
    startup_command: './run.sh +exec server.cfg +set sv_licenseKey {{LICENSE_KEY}}',
    config_schema: {
      files: ['server.cfg'],
      startup: ['LICENSE_KEY', 'TXADMIN_PORT'],
    },
    variables: [
      { key: 'LICENSE_KEY', name: 'Cfx.re License Key', description: 'Server key from Cfx.re portal', default_value: 'cfxk_demo_0192847192', user_viewable: true, user_editable: true, rules: 'required|string' },
      { key: 'TXADMIN', name: 'Enable txAdmin Web', description: 'Launch with txAdmin interface', default_value: '1', user_viewable: true, user_editable: true, rules: 'boolean' },
    ],
    version: 'fx-b9120',
    author: 'Cfx Community',
    rating: 4.9,
    downloads: 7850,
    official: false,
    description: 'Grand Theft Auto V multiplayer server container with full txAdmin dashboard integration and MySQL connection helper.',
    readme: 'One-click MariaDB database provisioning available in databases tab.',
  },
  {
    id: 'egg_valheim',
    name: 'Valheim Dedicated Server',
    game: 'Valheim',
    category: 'games',
    icon: 'Shield',
    docker_image: 'ghcr.io/pterodactyl/games:valheim',
    startup_command: './valheim_server.x86_64 -name "{{SERVER_NAME}}" -port {{SERVER_PORT}} -world "{{WORLD_NAME}}" -password "{{SERVER_PASSWORD}}"',
    config_schema: {
      files: ['start_valheim.sh'],
      startup: ['SERVER_NAME', 'WORLD_NAME', 'SERVER_PASSWORD'],
    },
    variables: [
      { key: 'SERVER_NAME', name: 'Server Name', description: 'Valheim world name in server browser', default_value: 'Valheim Viking Realm', user_viewable: true, user_editable: true, rules: 'required|string' },
      { key: 'WORLD_NAME', name: 'World Save Name', description: 'Save file identifier', default_value: 'Dedicated', user_viewable: true, user_editable: true, rules: 'required|string' },
      { key: 'SERVER_PASSWORD', name: 'Password', description: 'Join password (min 5 chars)', default_value: 'secret123', user_viewable: true, user_editable: true, rules: 'required|string|min:5' },
    ],
    version: '0.218.15',
    author: 'ControlPanel Core',
    rating: 4.8,
    downloads: 6200,
    official: true,
    description: 'Native Linux dedicated server container for Valheim with BepInEx mod loader support and automatic world backups.',
    readme: 'Crossplay enabled with standard UDP port forwarding.',
  },
];

export const INITIAL_SERVERS: Server[] = [
  {
    id: 'srv_mc_kyiv',
    uuid: 'a8f3b20c-1194-4d89-9e81-2244917a80b1',
    name: 'Kyiv Craft Survival [1.21.4]',
    description: 'Main production Minecraft SMP server with 80+ plugins and dynmap',
    game: 'Minecraft: Java Edition',
    game_icon: 'Pickaxe',
    egg_id: 'egg_minecraft_paper',
    node_id: 'node_fra_01',
    owner_id: 'usr_superadmin_01',
    owner_email: 'admin@controlpanel.gg',
    status: 'running',
    limits: {
      cpu_percent: 400, // 4 vCores
      ram_mb: 16384,    // 16 GB
      disk_mb: 61440,   // 60 GB
      io_priority: 500,
      swap_mb: 2048,
    },
    current_stats: {
      cpu_percent: 64.2,
      ram_mb: 11420,
      disk_mb: 24800,
      net_rx_kb: 4210,
      net_tx_kb: 8940,
      uptime_seconds: 483200,
      players_online: 47,
      players_max: 100,
    },
    tags: ['vip', 'production', 'smp-network'],
    docker_image: 'ghcr.io/pterodactyl/yolks:java_21',
    startup_command: 'java -Xms128M -XX:MaxRAMPercentage=95.0 -jar paper.jar nogui',
    environment_variables: {
      SERVER_JARFILE: 'paper.jar',
      BUILD_NUMBER: 'latest',
      VIEW_DISTANCE: '12',
    },
    ports: [
      { port: 25565, protocol: 'tcp', primary: true, notes: 'Main Minecraft Game Port' },
      { port: 8123, protocol: 'tcp', primary: false, notes: 'Dynmap Web Interface' },
      { port: 24454, protocol: 'udp', primary: false, notes: 'Simple Voice Chat Mod' },
    ],
    network_isolated: true,
    auto_restart_on_crash: true,
    created_at: '2026-01-20T14:22:00Z',
    updated_at: '2026-03-10T11:00:00Z',
  },
  {
    id: 'srv_cs2_comp',
    uuid: '7d92ef11-0044-42b7-8491-aa94101e4bb2',
    name: 'CS2 Competitive Arena #1 (128t)',
    description: 'Tournament & Scrims 5v5 competitive server with MatchZy',
    game: 'Counter-Strike 2',
    game_icon: 'Crosshair',
    egg_id: 'egg_cs2',
    node_id: 'node_waw_02',
    owner_id: 'usr_superadmin_01',
    owner_email: 'admin@controlpanel.gg',
    status: 'running',
    limits: {
      cpu_percent: 300,
      ram_mb: 8192,
      disk_mb: 40960,
      io_priority: 700,
      swap_mb: 0,
    },
    current_stats: {
      cpu_percent: 48.5,
      ram_mb: 5120,
      disk_mb: 32400,
      net_rx_kb: 1820,
      net_tx_kb: 3400,
      uptime_seconds: 182400,
      players_online: 10,
      players_max: 12,
    },
    tags: ['esports', 'scrims', 'warsaw'],
    docker_image: 'ghcr.io/pterodactyl/games:source2',
    startup_command: './cs2/game/bin/linuxsteamrt64/cs2 -dedicated +ip 0.0.0.0 -port 27015 +map de_mirage',
    environment_variables: {
      SRCDS_MAP: 'de_mirage',
      MAXPLAYERS: '12',
    },
    ports: [
      { port: 27015, protocol: 'both', primary: true, notes: 'CS2 Game & Query' },
      { port: 27020, protocol: 'both', primary: false, notes: 'SourceTV Relay' },
    ],
    network_isolated: true,
    auto_restart_on_crash: true,
    created_at: '2026-02-01T09:15:00Z',
    updated_at: '2026-03-12T16:40:00Z',
  },
  {
    id: 'srv_rust_wipe',
    uuid: '99a18d22-5501-447a-8f12-33cc9129ef99',
    name: 'Rust Vanilla 2x | Solo/Duo/Trio',
    description: 'Weekly Thursday wipe, high tickrate anti-cheat protected',
    game: 'Rust',
    game_icon: 'Flame',
    egg_id: 'egg_rust',
    node_id: 'node_fra_01',
    owner_id: 'usr_client_02',
    owner_email: 'danilo.rust@gmail.com',
    status: 'running',
    limits: {
      cpu_percent: 600,
      ram_mb: 24576,
      disk_mb: 81920,
      io_priority: 900,
      swap_mb: 4096,
    },
    current_stats: {
      cpu_percent: 78.9,
      ram_mb: 18250,
      disk_mb: 46200,
      net_rx_kb: 9400,
      net_tx_kb: 14200,
      uptime_seconds: 64200,
      players_online: 184,
      players_max: 200,
    },
    tags: ['rust-wipe', 'high-pop', 'vip'],
    docker_image: 'ghcr.io/pterodactyl/games:rust',
    startup_command: './RustDedicated -batchmode +server.port 28015 +server.seed 44919',
    environment_variables: {
      SERVER_SEED: '44919',
      WORLD_SIZE: '4250',
      OXIDE: '1',
    },
    ports: [
      { port: 28015, protocol: 'both', primary: true, notes: 'Rust Game' },
      { port: 28016, protocol: 'tcp', primary: false, notes: 'Rust+ App Companion' },
      { port: 28082, protocol: 'tcp', primary: false, notes: 'RCON Remote Console' },
    ],
    network_isolated: true,
    auto_restart_on_crash: true,
    created_at: '2026-02-14T18:30:00Z',
    updated_at: '2026-03-18T20:10:00Z',
  },
  {
    id: 'srv_palworld_realm',
    uuid: '44c81a20-3321-419b-a010-0987efba9923',
    name: 'Palworld Explorers Guild',
    description: 'Casual community realm with 3x experience and fast breeding',
    game: 'Palworld',
    game_icon: 'Gamepad2',
    egg_id: 'egg_palworld',
    node_id: 'node_hel_01',
    owner_id: 'usr_reseller_01',
    owner_email: 'partner@eugames.cloud',
    status: 'running',
    limits: {
      cpu_percent: 400,
      ram_mb: 16384,
      disk_mb: 51200,
      io_priority: 600,
      swap_mb: 4096,
    },
    current_stats: {
      cpu_percent: 34.1,
      ram_mb: 12100,
      disk_mb: 18400,
      net_rx_kb: 1200,
      net_tx_kb: 2100,
      uptime_seconds: 96400,
      players_online: 18,
      players_max: 32,
    },
    tags: ['casual', 'reseller-tier'],
    docker_image: 'ghcr.io/pterodactyl/games:palworld',
    startup_command: './PalServer.sh -port=8211 -players=32 -useperfthreads',
    environment_variables: {
      MAX_PLAYERS: '32',
      SERVER_NAME: 'ControlPanel Palworld Realm',
    },
    ports: [
      { port: 8211, protocol: 'udp', primary: true, notes: 'Palworld Main Port' },
    ],
    network_isolated: true,
    auto_restart_on_crash: true,
    created_at: '2026-02-25T11:00:00Z',
    updated_at: '2026-03-15T09:20:00Z',
  },
  {
    id: 'srv_valheim_viking',
    uuid: '11e99214-88aa-4c22-b910-feef33918420',
    name: 'Valheim Nordic Survival [Ashlands]',
    description: 'Hardcore Ashlands expedition server with automated nightly world backups',
    game: 'Valheim',
    game_icon: 'Shield',
    egg_id: 'egg_valheim',
    node_id: 'node_hel_01',
    owner_id: 'usr_superadmin_01',
    owner_email: 'admin@controlpanel.gg',
    status: 'running',
    limits: {
      cpu_percent: 200,
      ram_mb: 8192,
      disk_mb: 20480,
      io_priority: 400,
      swap_mb: 1024,
    },
    current_stats: {
      cpu_percent: 32.4,
      ram_mb: 4890,
      disk_mb: 7420,
      net_rx_kb: 4200,
      net_tx_kb: 8150,
      uptime_seconds: 420000,
      players_online: 8,
      players_max: 10,
    },
    tags: ['valheim', 'ashlands', 'hardcore'],
    docker_image: 'ghcr.io/pterodactyl/games:valheim',
    startup_command: './valheim_server.x86_64 -name "Valheim Nordic" -port 2456 -world "Ashlands" -password "viking2026"',
    environment_variables: {
      SERVER_NAME: 'Valheim Nordic Survival',
      WORLD_NAME: 'Ashlands',
      SERVER_PASSWORD: 'viking_shield',
    },
    ports: [
      { port: 2456, protocol: 'udp', primary: true, notes: 'Valheim Game & Query' },
      { port: 2457, protocol: 'udp', primary: false, notes: 'Steam Master Server' },
    ],
    network_isolated: true,
    auto_restart_on_crash: true,
    created_at: '2026-01-10T12:00:00Z',
    updated_at: '2026-03-01T15:30:00Z',
  },
  {
    id: 'srv_fivem_roleplay',
    uuid: '55bc901a-7721-4d1a-88ff-114477889922',
    name: 'Horizon State Roleplay (QBCore)',
    description: 'Heavy roleplay Los Santos with 200+ custom add-on cars',
    game: 'GTA V / FiveM',
    game_icon: 'Car',
    egg_id: 'egg_fivem',
    node_id: 'node_iad_01',
    owner_id: 'usr_client_03',
    owner_email: 'rp.director@horizon.games',
    status: 'offline',
    limits: {
      cpu_percent: 400,
      ram_mb: 16384,
      disk_mb: 71680,
      io_priority: 750,
      swap_mb: 2048,
    },
    current_stats: {
      cpu_percent: 0,
      ram_mb: 0,
      disk_mb: 41200,
      net_rx_kb: 0,
      net_tx_kb: 0,
      uptime_seconds: 0,
      players_online: 0,
      players_max: 64,
    },
    tags: ['fivem', 'maintenance', 'us-east'],
    docker_image: 'ghcr.io/pterodactyl/games:fivem',
    startup_command: './run.sh +exec server.cfg',
    environment_variables: {
      LICENSE_KEY: 'cfxk_demo_0192847192',
      TXADMIN: '1',
    },
    ports: [
      { port: 30120, protocol: 'both', primary: true, notes: 'FXServer Primary' },
      { port: 40120, protocol: 'tcp', primary: false, notes: 'txAdmin Web Dashboard' },
    ],
    network_isolated: true,
    auto_restart_on_crash: false,
    created_at: '2026-03-02T19:00:00Z',
    updated_at: '2026-03-21T04:15:00Z',
  },
];

export const INITIAL_QUEUE_JOBS: QueueJob[] = [
  {
    id: 'job_mig_881',
    title: 'Server Migration: #srv_rust_wipe (waw2 -> fra1)',
    type: 'migration',
    status: 'processing',
    progress: 74,
    current_step: 'Rsyncing volume snapshots: 34.2 GB / 46.2 GB',
    started_at: '2026-03-22T18:34:10Z',
    server_id: 'srv_rust_wipe',
    node_id: 'node_fra_01',
  },
  {
    id: 'job_bup_104',
    title: 'Automated Nightly Backup: Kyiv Craft Survival',
    type: 'backup',
    status: 'completed',
    progress: 100,
    current_step: 'Uploaded to S3 MinIO storage driver (SHA256 verified)',
    started_at: '2026-03-22T03:00:00Z',
    duration_seconds: 142,
    server_id: 'srv_mc_kyiv',
  },
  {
    id: 'job_egg_092',
    title: 'Marketplace Egg Sync: CS2 Sub-tick Update 2026.02',
    type: 'egg_install',
    status: 'completed',
    progress: 100,
    current_step: 'Schema validated against PostgreSQL jsonb field',
    started_at: '2026-03-21T21:12:00Z',
    duration_seconds: 8,
  },
  {
    id: 'job_bulk_044',
    title: 'Bulk Action: Upgrade CPU limits +25% on Tag [vip]',
    type: 'bulk_action',
    status: 'queued',
    progress: 0,
    current_step: 'Waiting in Horizon queue: queue:priority_high',
    started_at: '2026-03-22T18:37:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud_991',
    actor_name: 'Maksym Bondar',
    actor_email: 'admin@controlpanel.gg',
    actor_role: 'superadmin',
    action: 'server:limits:update',
    entity_type: 'server',
    entity_name: 'Kyiv Craft Survival [1.21.4]',
    entity_id: 'srv_mc_kyiv',
    diff: [
      { field: 'limits.ram_mb', old_value: 12288, new_value: 16384 },
      { field: 'limits.cpu_percent', old_value: 300, new_value: 400 },
    ],
    ip: '193.106.31.2',
    via: 'UI',
    created_at: '2026-03-22T17:15:30Z',
  },
  {
    id: 'aud_990',
    actor_name: 'System Worker (Horizon)',
    actor_email: 'worker@controlpanel.internal',
    actor_role: 'system',
    action: 'node:maintenance:enable',
    entity_type: 'node',
    entity_name: 'US-Virginia-01 (East Edge)',
    entity_id: 'node_iad_01',
    diff: [
      { field: 'maintenance_mode', old_value: false, new_value: true },
      { field: 'reason', old_value: null, new_value: 'Kernel livepatch upgrade scheduled' },
    ],
    ip: '127.0.0.1',
    via: 'CLI',
    created_at: '2026-03-22T16:02:11Z',
  },
  {
    id: 'aud_989',
    actor_name: 'Danilo Rust',
    actor_email: 'danilo.rust@gmail.com',
    actor_role: 'user',
    action: 'server:power:restart',
    entity_type: 'server',
    entity_name: 'Rust Vanilla 2x | Solo/Duo/Trio',
    entity_id: 'srv_rust_wipe',
    diff: [
      { field: 'status', old_value: 'running', new_value: 'starting' },
      { field: 'signal', old_value: null, new_value: 'SIGTERM -> clean stop' },
    ],
    ip: '91.222.140.8',
    via: 'API',
    created_at: '2026-03-22T14:44:00Z',
  },
  {
    id: 'aud_988',
    actor_name: 'Maksym Bondar',
    actor_email: 'admin@controlpanel.gg',
    actor_role: 'superadmin',
    action: 'security:token:create',
    entity_type: 'token',
    entity_name: 'WHMCS Automation Integration Key',
    entity_id: 'tok_whmcs_live',
    diff: [
      { field: 'scopes', old_value: [], new_value: ['servers:create', 'servers:suspend', 'servers:delete'] },
      { field: 'ip_whitelist', old_value: [], new_value: ['185.220.101.44/32'] },
    ],
    ip: '193.106.31.2',
    via: 'UI',
    created_at: '2026-03-21T18:20:00Z',
  },
];

export const INITIAL_API_TOKENS: ApiToken[] = [
  {
    id: 'tok_01',
    name: 'CI/CD Automated Deployment',
    token_prefix: 'cpt_live_9a781...',
    scopes: ['servers:read', 'servers:power', 'servers:files:write'],
    allowed_ips: ['194.26.29.0/24'],
    expires_at: '2026-12-31T23:59:59Z',
    last_used_at: '2026-03-22T18:10:00Z',
    created_at: '2026-01-10T11:00:00Z',
  },
  {
    id: 'tok_02',
    name: 'Backup Auditor Scoped Token',
    token_prefix: 'cpt_live_44b12...',
    scopes: ['servers:backup:read', 'servers:backup:create'],
    allowed_ips: ['*'],
    expires_at: '2026-06-30T23:59:59Z',
    last_used_at: '2026-03-22T03:02:00Z',
    created_at: '2026-02-01T15:20:00Z',
  },
];

export const INITIAL_SESSIONS: ActiveSession[] = [
  {
    id: 'ses_cur',
    device: 'Apple MacBook Pro (M3 Max)',
    browser: 'Chrome 123.0 / macOS Sonoma',
    ip: '193.106.31.2',
    location: 'Kyiv, Ukraine',
    current: true,
    last_active: 'Зараз (активна сесія)',
  },
  {
    id: 'ses_02',
    device: 'Workstation ThinkPad P16',
    browser: 'Firefox Developer 124 / Fedora Linux',
    ip: '178.62.199.12',
    location: 'Warsaw, Poland',
    current: false,
    last_active: 'Вчора о 22:40',
  },
  {
    id: 'ses_03',
    device: 'iPhone 16 Pro',
    browser: 'Mobile Safari 18.2 / iOS',
    ip: '94.153.28.14',
    location: 'Lviv, Ukraine',
    current: false,
    last_active: '3 дні тому',
  },
];

export const INITIAL_BILLING_PLANS: BillingPlan[] = [
  {
    id: 'plan_starter',
    name: 'Starter Gamer',
    price_usd: 4.99,
    memory_gb: 4,
    cpu_cores: 2,
    disk_gb: 30,
    backups_allowed: 3,
    databases_allowed: 1,
    popular: false,
    description: 'Ідеально для невеликого серверу Minecraft або CS2 для компанії друзів.',
  },
  {
    id: 'plan_pro',
    name: 'Pro Guild Cloud',
    badge: 'Найпопулярніший',
    price_usd: 14.99,
    memory_gb: 16,
    cpu_cores: 4,
    disk_gb: 80,
    backups_allowed: 10,
    databases_allowed: 3,
    popular: true,
    description: 'Високопродуктивні ядра Ryzen 7950X для Rust, Palworld та великих SMP серверів.',
  },
  {
    id: 'plan_ultra',
    name: 'Enterprise Dedicated',
    badge: 'VIP Хостинг',
    price_usd: 39.99,
    memory_gb: 32,
    cpu_cores: 8,
    disk_gb: 200,
    backups_allowed: 30,
    databases_allowed: 10,
    popular: false,
    description: 'Пріоритетне розміщення в ізольованій Docker-мережі з гарантованим NVMe I/O.',
  },
];

export const INITIAL_WEBHOOKS: WebhookEndpoint[] = [
  {
    id: 'wh_01',
    name: 'Discord Incident Notification Webhook',
    url: 'https://discord.com/api/webhooks/121884910283/aBcDeFgHiJkLmNoP',
    events: ['server.crashed', 'node.offline', 'backup.failed'],
    secret: 'whsec_99481abf0192847118274619a9',
    active: true,
    last_delivery_status: '200 OK',
    last_delivery_time: '2026-03-22T16:02:12Z',
  },
  {
    id: 'wh_02',
    name: 'Billing WHMCS Webhook Sync',
    url: 'https://billing.apexcloud.eu/modules/servers/controlpanel/callback.php',
    events: ['server.created', 'server.suspended', 'server.unsuspended'],
    secret: 'whsec_229188471bccaaeef881920394',
    active: true,
    last_delivery_status: '200 OK',
    last_delivery_time: '2026-03-22T17:15:35Z',
  },
];
